### ISSUE TITLE
install-complete.txt similarities in db

### ISSUE THREAD

**Issue by leblancmeneses** [cdandoy/DbPop#55]
I have dbpop populating data in k8s environment. However, if the instance is upgraded dbpop runs again.  it would be nice if dbpop stored metadata inside the db.  I could then check if the schema exists to know whether dbpop has already ran.

I run the process as:
init schema
start dbpop
run flyway <-- this is here to support more than just the dbpop environment.

For now I can accomplish this with a flyway script, however, a universal solution would be something maintained inside dbpop.

Thanks,

**Comment by leblancmeneses** [comment]
my current workaround:

```
            /opt/mssql-tools18/bin/sqlcmd \
              -C -b -S "$MSSQL_SERVER" -U "$TARGET_USERNAME" -P "$TARGET_PASSWORD" \
              -Q "CREATE SCHEMA [DbPop];"

            result=$?
            if [ $result -ne 0 ] ; then
              echo "do not rerun dbpop";
              exit 0;
            fi
```

**Comment by cdandoy** [comment]
If DbPop does not run, how does the developer reset the data?

**Comment by leblancmeneses** [comment]
this needs to run as part of headless non user interactive also.  

In headless non interactive environment how do I know dbpop failed ?  most apps would exit 1 or similar.

Example:
![image](https://user-images.githubusercontent.com/730804/219898975-9a45edf4-abcd-4cf6-bd45-1d136413e1c7.png)

right now the only hook i know of is watching: /var/opt/dbpop/setup/install-complete.txt

what about errors?

**Comment by cdandoy** [comment]
After startup, DbPop starts a background task to load the base dataset.
It does that so the developer has a populated database to work with, without having to load the dataset from the DbPop UI.

What you call an headless environment is most likely a build environment for automated tests. In that case it would make sense to not load a dataset at all since every automated test would start by reloading the data.
To disable that behavior, define an environment variable: `dbpopd.startup.loadDatasets=false`.

If you want to test if a specific dataset can be loaded, you can use the API. See http://localhost:7104/swagger-ui/#/populate/populate.

DbPop becomes functional only when it can connect to the database, and SQL Server may take a while to startup, especially when the container starts for the first time.
You can check of DbPop is connected to the database using the API. See http://localhost:7104/swagger-ui/#/default/site.
